export {default as Navbar} from "./navbar/Navbar";
export {default as Header} from "./header/Header";
export {default as Movie1} from "./movie1/Movie1";
export {default as Space} from "./space/Space";
export {default as Movie2} from "./movie2/Movie2";
export {default as Movie3} from "./movie3/Movie3";
export {default as Movie4} from "./movie4/Movie4";
export {default as Movie5} from "./movie5/Movie5";
export {default as Footer} from "./footer/Footer";
